### ISSUE TITLE
Error attempting to process sell_fulfillment_v1_oas3.json

### ISSUE THREAD

**Issue by MarErm27** [guardrail-dev/guardrail#1530]
Hello, I've tried to build this Ebay spec
```
https://developer.ebay.com/api-docs/master/sell/fulfillment/openapi/3/sell_fulfillment_v1_oas3.json
```
using Guardrail CLI
```
guardrail       --client --specPath sell_fulfillment_v1_oas3.json --outputPath src/main/scala --packageName com.twilio.messaging.console.clients.events
```
I got this output:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Error: Error attempting to process sell_fulfillment_v1_oas3.json:

java.net.URISyntaxException: Illegal character in authority at index 8: https://api.ebay.com{basePath}
        at dev.guardrail.Common$.$anonfun$prepareDefinitions$5(Common.scala:53)
          ...
        at dev.guardrail.Common$.$anonfun$prepareDefinitions$3(Common.scala:52)
          ...
        at dev.guardrail.core.IndexedDistributive$.cotraverse(IndexedDistributive.scala:18)
        at dev.guardrail.core.IndexedDistributiveImplicits$IndexedDistributiveSyntax.cotraverse(IndexedDistributive.scala:24)
        at dev.guardrail.core.IndexedDistributiveImplicits$IndexedDistributiveSyntax.flatExtract(IndexedDistributive.scala:27)
        at dev.guardrail.Common$.$anonfun$prepareDefinitions$1(Common.scala:48)
        at dev.guardrail.Target$$anon$1.traverse(Target.scala:61)
        at dev.guardrail.Target$$anon$1.traverse(Target.scala:29)
          ...
        at dev.guardrail.Target$$anon$1.map(Target.scala:29)
          ...
        at dev.guardrail.Common$.prepareDefinitions(Common.scala:42)
        at dev.guardrail.core.CoreTermInterp.$anonfun$processArgSet$17(CoreTermInterp.scala:135)
        at dev.guardrail.TargetValue.flatMap(Target.scala:103)
        at dev.guardrail.core.CoreTermInterp.$anonfun$processArgSet$16(CoreTermInterp.scala:133)
        at dev.guardrail.TargetValue.flatMap(Target.scala:103)
        at dev.guardrail.core.CoreTermInterp.$anonfun$processArgSet$15(CoreTermInterp.scala:132)
        at dev.guardrail.TargetValue.flatMap(Target.scala:103)
        at dev.guardrail.core.CoreTermInterp.$anonfun$processArgSet$14(CoreTermInterp.scala:131)
        at dev.guardrail.ReadSwagger$.$anonfun$readSwagger$4(ReadSwagger.scala:25)
        at dev.guardrail.TargetValue.flatMap(Target.scala:103)
        at dev.guardrail.ReadSwagger$.readSwagger(ReadSwagger.scala:25)
        at dev.guardrail.runner.GuardrailRunner.$anonfun$guardrailRunner$3(GuardrailRunner.scala:18)
          ...
        at dev.guardrail.runner.GuardrailRunner.$anonfun$guardrailRunner$2(GuardrailRunner.scala:16)
        at dev.guardrail.TargetValue.flatMap(Target.scala:103)
        at dev.guardrail.runner.GuardrailRunner.$anonfun$guardrailRunner$1(GuardrailRunner.scala:16)
        at dev.guardrail.cli.CLICommon.$anonfun$run$8(CLICommon.scala:191)
        at dev.guardrail.TargetValue.flatMap(Target.scala:103)
        at dev.guardrail.cli.CLICommon.run(CLICommon.scala:190)
        at dev.guardrail.cli.CLICommon.run$(CLICommon.scala:173)
        at dev.guardrail.cli.CLI$.run(CLI.scala:3)
        at dev.guardrail.cli.CLICommon.processArgs(CLICommon.scala:73)
        at dev.guardrail.cli.CLICommon.processArgs$(CLICommon.scala:70)
        at dev.guardrail.cli.CLI$.processArgs(CLI.scala:3)
        at dev.guardrail.cli.CLI$.main(CLI.scala:9)
        at dev.guardrail.cli.CLI.main(CLI.scala)
          ...
```

I was wondering if maybe I use the CLI wrongly, how to generate the spec?

**Comment by MarErm27** [comment]
After I replaced all {basePath} variables with "/sell/fulfillment/v1" in the JSON spec, I got this error: 
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Unable to generate decoder for application/octet-stream (.paths./payment_dispute/{payment_dispute_id}/fetch_evidence_content.operations.GET.produces[0])
Error: No decoders available (.paths./payment_dispute/{payment_dispute_id}/fetch_evidence_content.operations.GET.produces)
```

**Comment by MarErm27** [comment]
Guardrail unable to create a decoder here:

https://github.com/guardrail-dev/guardrail/blob/47bc1c22fbb05516944f9adede066576d3832040/modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpHelper.scala#L22

**Comment by blast-hardcheese** [comment]
Hello! So, looking...

```json
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/octet-stream": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
```
seems as though `application/octet-stream` doesn't quite agree with the `schema: array[string]`, should that be an `application/json`?

**Comment by MarErm27** [comment]
@blast-hardcheese Hello, Devon Stewart 
I have replaced ```application/octet-stream``` with ```application/json`, and I have the generated code now, thank you. The generated code is not a project, how to turn it into a project to make it possible to deploy it locally to Maven?
I need to run ```mvn clean install``` to do it, but the generated code don't have a pom.xml file. How to install it?

**Comment by blast-hardcheese** [comment]
@MarErm27 Please see any of the applicable (and compilable) samples in the [`guardrail-sample`](https://github.com/topics/guardrail-sample) topic.

guardrail is intended to coexist inside existing projects with whatever versions of dependencies you already have, so it doesn't generate or manage your pom for you.

You can use dependabot in order to keep your dependencies up-to-date, and if you find a change that prevents guardrail-generated code from compiling with new versions of whatever libraries you need, that should be opened as an issue.

**Comment by blast-hardcheese** [comment]
Additionally, a consideration is that idiomatic code generation in guardrail is to use the build-tool plugins, `sbt-guardrail`, `guardrail-maven-plugin`, `guardrail-gradle-plugin`, and the code is generated and regenerated every time you compile, you only commit _your_ code, the generated code is not committed into your repository. That may help make sense of how the samples are structured.

**Comment by MarErm27** [comment]
@blast-hardcheese I use Play WS as HTTP client, it is build on top of AKKA HTTP. I think I need to look at this example:
https://github.com/guardrail-dev/guardrail-sample-sbt-akkahttp

What to do with this example? Do I need to merge it in my Play project? I see that I can't automatically keep my Ebay client dependencies with Guardrail because it is not support Ebay OpenAPI 3 schemas. So I think I just need to manually generate the Ebay client. Can I create a new maven project with Idea Intellij, then add the generated code, and then do ```mvn clean install``` that? Or it is not recommended scenario for my case?

**Comment by blast-hardcheese** [comment]
@MarErm27 Interesting! In that case, just either sbt or maven, as described, with a set of dependencies that you determine makes sense for your project (perhaps just akka-http, using the dependencies in the sample you linked earlier, using `sbt publishLocal` or `mvn install`, including the ephemerally generated sources in the generated artifact.

**Comment by blast-hardcheese** [comment]
There's no consideration between generating sources by `guardrail-cli` or using build tool plugins, the artifact would both include the full generated sources.

**Comment by MarErm27** [comment]
@blast-hardcheese 
I have cloned the [AKKA HTTP](https://github.com/guardrail-dev/guardrail-sample-sbt-akkahttp) example and put the generated code under src/main/scala directory.
To deploy the project to [reposilite](https://reposilite.com/) I follow the [instruction](https://kihats.medium.com/custom-self-hosted-maven-repository-cbb778031f68)

I was wondering if you know how to convert this from maven pom to sbt?
```
<distributionManagement>
    <repository>
        <id>my-repository</id>
        <url>http://localhost:8080/releases</url>
    </repository>
</distributionManagement>
```
Which command will do ```mvn deploy``` in sbt?

**Comment by blast-hardcheese** [comment]
@MarErm27 Suggest taking a look at https://www.scala-sbt.org/1.x/docs/Publishing.html , then `sbt publish` will do it

**Comment by MarErm27** [comment]
@blast-hardcheese 
Hello, Devon Stewart how to specify Scala version to 2.13.8?
Is this example for Scala 2.13.8?
https://github.com/guardrail-dev/guardrail-sample-sbt-akkahttp

I met problems when I tried to import it to 2.13.8 Scala project, can it be related to version?

**Comment by blast-hardcheese** [comment]
@MarErm27 There is no requirement from guardrail as to the version of the Scala compiler, I would evaluate which dependencies you are using to see if they are available for 2.13.8, perhaps the sample includes some old dependencies, I don't know what error you're getting.

**Comment by MarErm27** [comment]
@blast-hardcheese here is the error: https://github.com/MarErm27/generated_ebay_client/issues/2

**Comment by MarErm27** [comment]
@blast-hardcheese 
Errors when set scalaVersion to "2.13.8"
https://github.com/MarErm27/generated_ebay_client/issues/3
How to fix it?

**Comment by blast-hardcheese** [comment]
@MarErm27 It looks like the `import io.circe._` imports `Error`, which conflicts with the `Error` defined in the eBay spec. This works: https://github.com/MarErm27/generated_ebay_client/pull/4

**Comment by MarErm27** [comment]
@blast-hardcheese 
Hello, Devon Stewart, thank you so much, I imported the SDK to my Play project

When I'm trying to create a new OrderClient it demands implicit:
```new sell.fulfillment.order.OrderClient(No implicits found for parameters httpClient: HttpRequest => Future[HttpResponse], mat: Materializer)```

Since Play is build on top of AKKA HTTP I was wondering if I still can provide the implicits?
I have found materializaer in play: ```import play.api.Play.materializer```
I can't find actorSystem ```import App.actorSystem``` because I don't have the App. Is it somewhere else?

**Comment by blast-hardcheese** [comment]
The ActorSystem is not required, though you need to supply a http client. The alternate constructor `httpClient` may be easier to understand what's going on, you need to create an akka-http http client and pass that to the guardrail client.

guardrail generated clients don't know anything about how to connect to a socket, they exist in the business logic space. You can supply anything that fits that type signature, like `Http().singleRequest`, or alternately a pooling client.

**Comment by MarErm27** [comment]
@blast-hardcheese May you show an example?

**Comment by blast-hardcheese** [comment]
> @blast-hardcheese May you show an example?

The official documentation would say it better than I can: https://doc.akka.io/docs/akka-http/current/client-side/request-level.html

I would appreciate suggestions or a PR on how to improve the https://guardrail.dev/ documentation, based on your findings

**Comment by MarErm27** [comment]
@blast-hardcheese 
It would be a pleasure for me to share my findings with Guardrail, but I'm still trying to make it work, may you take a look?

https://github.com/MarErm27/Using-generated-eBay-client/blob/main/app/controllers/EbayClient.scala

**Comment by blast-hardcheese** [comment]
It looks very close to what I would expect, you can try
```scala
    val orderClient = sell.fulfillment.order.OrderClient.httpClient(client)
```

to use the idiomatic constructor, instead of specifying the implicits. Other than that it looks like it should work, are you still having problems?

**Comment by MarErm27** [comment]
@blast-hardcheese there are a few problems:
1. 
![image](https://user-images.githubusercontent.com/56219126/178078819-098d36c0-f302-4787-96b8-c1baed031a0a.png)
2. 
![image](https://user-images.githubusercontent.com/56219126/178078854-946f1d23-58aa-4eaf-8a19-4c793b052b70.png)
3.
![image](https://user-images.githubusercontent.com/56219126/178078881-c8a24626-d43f-4152-a9c7-136fb8351711.png)

**Comment by blast-hardcheese** [comment]
1. Change `Http().singleRequest` to `Http().singleRequest(_)`
2. I don't understand the question, that is the result type of calling the function.
2a. `Future` because it's async
2b. `Either[Throwable, HttpResponse]` represents both network as well as http failures, distinctly, that you can handle or ignore at your discretion
2c. `GetOrdersResponse` is a type representing the success and failure results. You can `match` on the constituent types to handle successes or failure response codes and body encodings (There's a convenience function, `fold`, which you can use if you find there's enough repetition in the error code structures in the API you consume, but it's not necessary.)

**Comment by MarErm27** [comment]
@blast-hardcheese 
I think getOrders suppose to return Future[GetOrdersResponse]

**Comment by MarErm27** [comment]
@blast-hardcheese 
Error with Http().singleRequest(_):
![image](https://user-images.githubusercontent.com/56219126/178080502-929ad2a1-2ee3-477d-ae30-3171cab3ed08.png)

**Comment by blast-hardcheese** [comment]
> @blast-hardcheese 
> Error with Http().singleRequest(_):
> ![image](https://user-images.githubusercontent.com/56219126/178080502-929ad2a1-2ee3-477d-ae30-3171cab3ed08.png)
> 

https://guardrail.dev/scala/akka-http/generating-clients#separation-of-protocol-concerns-from-api-level-concerns

**Comment by blast-hardcheese** [comment]
> @blast-hardcheese 
> I think getOrders suppose to return Future[GetOrdersResponse]

There are runtime errors, represented in the exception, as well as the potential for an error that was not included in the OpenAPI specification, that's why there are these two possible errors reserved.

[`valueOr`](https://github.com/typelevel/cats/blob/main/core/src/main/scala/cats/data/EitherT.scala#L265) could permit

```scala
getOrders(...).valueOr({ errs => throw new Exception(errs.toString()) })
```

but I would advise against it. If you're familiar with `Either#fold`, a similar approach will work here, and give you the `Future[A]` you can use to interoperate with the rest of your application.

Hopefully that helps!

**Comment by MarErm27** [comment]
@blast-hardcheese 
I was wondering if you may take a look: https://github.com/MarErm27/Using-generated-eBay-client/issues/1

**Comment by blast-hardcheese** [comment]
I left a comment. I think `EitherT` can be useful, and if you don't need that use then translating the error case into a failed `Future` is ok

**Comment by MarErm27** [comment]
@blast-hardcheese 
https://guardrail.dev/scala/akka-http/generating-clients#separation-of-protocol-concerns-from-api-level-concerns

What is the difference here between singleRequestHttpClient and retryingHttpClient?
I see I can't replace singleRequestHttpClient with retryingHttpClient
 because it has another type. Can I use singleRequestHttpClient multiple times?

**Comment by MarErm27** [comment]
@blast-hardcheese 
Am I right that the general flow of working with Guardrail to generate an SDK  is:
1. Clone one of examples: https://github.com/topics/guardrail-sample
2.  Add spec. Change build.sbt extending guardrailTasks, for example
```
Compile / guardrailTasks := List(
  ScalaClient(file("sell_fulfillment_v1_oas3.json"), pkg="sell.fulfillment")
)
```
which says take file named ```sell_fulfillment_v1_oas3.json``` at the root of the example, generate the code and put it under ```sell.fulfillment``` directory.
3. Build the example.

That's it, enjoy the code. This is meant to work for all the SDK with Open API 3 specs. Right? Did I miss something?

**Comment by blast-hardcheese** [comment]
> That's it, enjoy the code

Effectively, yes. The intent is that because you never commit any generated code, you can always generate code during compile.

We cache the build output, so if the OpenAPI spec does not change, then we just use the cache, to improve compilation speed.

**Comment by blast-hardcheese** [comment]
> singleRequestHttpClient and retryingHttpClient are different types

The main thing is we need a `HttpRequest => Future[HttpResponse]`. However you get one, that's fine. You can even implement your own, based on `recover` from the first response passing the same `HttpRequest` again!

This method of not needing a specific implementation of client permits all kinds of use cases, like supplying functions that return static responses in your tests, so you can write without mocks, changing the implementation of the httpClient value based on different clients due to the different way different integrations work.

**Comment by MarErm27** [comment]
> > singleRequestHttpClient and retryingHttpClient are different types
> 
> The main thing is we need a `HttpRequest => Future[HttpResponse]`. However you get one, that's fine. You can even implement your own, based on `recover` from the first response passing the same `HttpRequest` again!
> 
> This method of not needing a specific implementation of client permits all kinds of use cases, like supplying functions that return static responses in your tests, so you can write without mocks, changing the implementation of the httpClient value based on different clients due to the different way different integrations work.

@blast-hardcheese I'm sorry, I don't understand. Here:
https://github.com/MarErm27/Using-generated-eBay-client/blob/dc8f4be7ff1fdf747450ac0a8252da58893b0c0c/app/controllers/EbayClient.scala#L25

I use singleRequestHttpClient as a parameter to httpClient
```
    implicit val client = singleRequestHttpClient
    val orderClient = sell.fulfillment.order.OrderClient.httpClient(client)(ec, mat)
```
but I can't just substitute singleRequestHttpClient with retryingHttpClient, it has another type. May you provide an example on how to use retryingHttpClient?

**Comment by blast-hardcheese** [comment]
> May you provide an example on how to use retryingHttpClient?

What is the type of the retrying client?

**Comment by MarErm27** [comment]
@blast-hardcheese 
![image](https://user-images.githubusercontent.com/56219126/178798837-9af3c41a-9bdf-4641-97ef-65ff6e0192b6.png)

It is ```(HttpRequest => Future[HttpResponse]) => HttpRequest => Future[HttpResponse]``` instead of ```HttpRequest => Future[HttpResponse]```

**Comment by blast-hardcheese** [comment]
so you have a singleRequestHttpClient() that looks like `HttpRequest => Future[HttpResponse]`, and the retryingHttpClient needs a `HttpRequest => Future[HttpResponse]` in order to produce a `HttpRequest => Future[HttpResponse]`...

**Comment by blast-hardcheese** [comment]
I'm not trying to be confusing, but learning to read the types in Scala and understand functions that take functions as arguments will go a long way to helping you succeed in Scala
