### ISSUE TITLE
`format` schema field warning

### ISSUE THREAD

**Issue by sammy-da** [guardrail-dev/guardrail#1597]
I have a schema defined like this:
```json
 {
      "type": "string",
      "description": "...",
      "format": "jwt"
}
```
the `sbt` build gives me a warning:
```
Warning: Deprecated behavior: Unsupported format 'jwt' for type 'string', falling back to String. Please switch definitions to x-scala-type for custom types. (.components.schemas.AccountToken)
```

I tried adding an  `"x-scala-type": "String",` field to the schema, but still getting the same warning.

**Comment by blast-hardcheese** [comment]
@sammy-da Hello, please excuse the delay in response.

You're very much correct! We treat `x-scala-type` preferentially, but still emit the warning, even if that value is never used.

I've just pushed up a fix to resolve this (sorry that merging that closed this issue before I had a chance to comment), I'll be releasing a new version of `guardrail-core` shortly. If you explicitly depend on that newer version in your `project/plugins.sbt` it will resolve this issue.

**Comment by blast-hardcheese** [comment]
https://github.com/guardrail-dev/guardrail/releases/tag/core-v0.75.3 is released, and

```scala
libraryDependencies += "dev.guardrail" %% "guardrail-core" % "0.75.3"
```

in your `project/plugins.sbt` should work as soon as the metadata syncs to maven central.

Thank you for the report!

**Comment by blast-hardcheese** [comment]
@sammy-da `sbt-guardrail` v0.75.1 [has been released](https://github.com/guardrail-dev/sbt-guardrail/releases/tag/v0.75.1), thanks for your patience!
