### ISSUE TITLE
Client (and maybe model?) generated duplicate argument params if named same

### ISSUE THREAD

**Issue by er1c** [guardrail-dev/guardrail#1642]
Here's a base component: 

<img width="840" alt="image" src="https://user-images.githubusercontent.com/64685/203610686-0538ec57-6c93-4d7e-9029-fdf73d4c7e67.png">

We have two different types (Supply and Demand) and have unique descriptions:

![image](https://user-images.githubusercontent.com/64685/203610908-3512ede4-d912-468a-9185-34404c158d5b.png)

The case class that gets generated has two `productType` instances:

```
case class SupplySubAccountUpdateData(
  name: String,
  displayName: String,
  description: Option[String] = None,
  disclaimer: Option[String] = None,
  imageUrl: Option[String] = None,
  notes: Option[String] = None,
  productType: Option[String] = None,
  subtextOverride: Option[String] = None, 
  integrationType: Option[SupplySubAccountIntegrationType] = None,
  dataShare: Option[String] = None,
  coBrand: Option[Boolean] = None,
  productType: Option[String] = None,
  subAccountOwners: Option[_root_.scala.Vector[SupplySubAccountOwnerCreateData]] = None
)
```

**Comment by blast-hardcheese** [comment]
Hey there, sorry for the radio silence on this issue, thanks for the report. As I'm pushing towards a 1.0 release, I'm trying to resolve some of these low-hanging issues.
