### ISSUE TITLE
Missing support for HTTP HEAD request for akka-http and http4s

### ISSUE THREAD

**Issue by abrighton** [guardrail-dev/guardrail#1682]
Support for HTTP HEAD is missing for akka-http and http4s (See code comments below):

In guardrail/modules/scala-http4s/src/main/scala/dev/guardrail/generators/scala/http4s/Http4sServerGenerator.scala:

```
  def httpMethodToHttp4s(method: HttpMethod): Target[Term.Name] = method match {
    case HttpMethod.DELETE => Target.pure(Term.Name("DELETE"))
    case HttpMethod.GET    => Target.pure(Term.Name("GET"))
    case HttpMethod.PATCH  => Target.pure(Term.Name("PATCH"))
    case HttpMethod.POST   => Target.pure(Term.Name("POST"))
    case HttpMethod.PUT    => Target.pure(Term.Name("PUT"))
    case HttpMethod.HEAD   => Target.pure(Term.Name("HEAD"))  // <------- Need to add this!
    case other             => Target.raiseUserError(s"Unknown method: ${other}")
  }
```

And in guardrail/modules/scala-akka-http/src/main/scala/dev/guardrail/generators/scala/akkaHttp/AkkaHttpServerGenerator.scala

```
  def httpMethodToAkka(method: HttpMethod): Target[Term] = method match {
    case HttpMethod.DELETE  => Target.pure(q"delete")
    case HttpMethod.GET     => Target.pure(q"get")
    case HttpMethod.PATCH   => Target.pure(q"patch")
    case HttpMethod.POST    => Target.pure(q"post")
    case HttpMethod.PUT     => Target.pure(q"put")
    case HttpMethod.OPTIONS => Target.pure(q"options")
    case HttpMethod.HEAD    => Target.pure(q"head")  // <----- Need to add this!
    case other              => Target.raiseUserError(s"Unknown method: ${other}")
  }
```
 I haven't tested this yet, but assume this is what is needed.

**Comment by blast-hardcheese** [comment]
This looks correct, can you open a PR with the proposed change?

**Comment by abrighton** [comment]
See https://github.com/guardrail-dev/guardrail/pull/1686

**Comment by blast-hardcheese** [comment]
- [scala-akka-http-v0.76.0](https://github.com/guardrail-dev/guardrail/releases/tag/scala-akka-http-v0.76.0)
- [scala-http4s-v0.76.0](https://github.com/guardrail-dev/guardrail/releases/tag/scala-http4s-v0.76.0)

have now been released. Please add something similar to

```sbt
libraryDependencies += "dev.guardrail" %% "guardrail-scala-akka-http" % "0.76.0"
```
to your `project/guardrail.sbt` in order to manually upgrade that module and get this functionality sooner, it will get picked up in the next `sbt-guardrail` release.

**Comment by blast-hardcheese** [comment]
Closing, thank you again!
