### ISSUE TITLE
How _extends keyword works in the release-drafter yaml?

### ISSUE THREAD

**Issue by victor-wang-anz** [guardrail-dev/guardrail#1760]
Hi there, 
I am also trying to implement release-drafter in a monorepo context, however the _extends keyword does not triggered. So I would like how this works here. Thanks

**Comment by blast-hardcheese** [comment]
Most likely due to the guardrail repo being public, I ran into this issue trying to use extends in private repositories as well.

I found the documentation somewhere, but I couldn't identify a good cause other than "this is how GitHub libraries are implemented".

**Comment by blast-hardcheese** [comment]
I hope you got it figured out, all the best 🙂
