### ISSUE TITLE
change codegen output location

### ISSUE THREAD

**Issue by sammy-da** [guardrail-dev/guardrail#1861]
Is it possible to change the output directory (`target/.../...`) to a custom one?

The motivation is that I want to check in the generated code into source control, because I switch branches often, and this works more seamlessly with the IDE.
(also I find myself wanting to see the generated code from time to time anyway)

(And yes, along with that i'd no longer run guardrail as part of `Compile`, but rather run it manually on demand when i wish to update the generated code. I've used this build approach with other codegenerators and it's worked well for me)

I'm not too worried about preventing manual modifications to the generated code (and if I were, I can just write a `diff` test to check for that in my CI. Actually my CI fails if git is dirty anyway)

**Comment by blast-hardcheese** [comment]
What may be more useful for you is the CLI driver, instead of the SBT plugin. It's packaged and available via coursier:

```shell
cs install --contrib guardrail
```

this will give you a `guardrail` CLI tool with all configuration parameters specified as CLI args (see `guardrail --help` for inspiration, though there may be drift between the docs and the [argument parser](https://github.com/guardrail-dev/guardrail/blob/master/modules/cli/src/main/scala/dev/guardrail/cli/CLICommon.scala#L113))

**Comment by blast-hardcheese** [comment]
Please feel free to follow up here if the above doesn't work for some reason, but for the time being I'll close this out as completed

**Comment by sammy-da** [comment]
Yep, that does sound like a good solution.
Couple followup questions:
- how do i pin to a specific version. i tried `cs install --contrib guardrail:2.13`
- ^ i don't think I understand how artifacts are versioned. Does a CLI version get released with every guardrail release?

**Comment by blast-hardcheese** [comment]
To pick a specific version you can specify the classpath of the various modules you want:

```bash
cs launch \
  dev.guardrail::guardrail-cli:0.71.0 \
  dev.guardrail::guardrail-scala-support:0.75.3 \
  dev.guardrail::guardrail-scala-akka-http:0.76.0 \
  -- \
  --defaults --framework akka-http --outputPath /tmp/src/main/scala \
  --client --specPath /tmp/spec.yml --packageName com.example \
  --server --specPath /tmp/spec.yml --packageName com.example
```

To pin a particular version of "everything", you can track the `guardrail-all` tags [here](https://github.com/guardrail-dev/guardrail-all/tags). When you install by way of coursier's `cs install --contrib`, it just picks the most recent `dev.guardrail::guardrail-all_2.13:...` jar. I haven't figured out a better way of doing that, unfortunately, as coursier needs a single coordinate for `cs install` to work.

Throwing the `cs launch` command with the various modules you want into a `guardrail.sh` seems useful,

```bash
#!/bin/sh

cs launch \
  dev.guardrail::guardrail-cli:0.71.0 \
  dev.guardrail::guardrail-scala-support:0.75.3 \
  dev.guardrail::guardrail-scala-akka-http:0.76.0 \
  -- "$@"
```
so you can just say

```bash
./guardrail.sh \
  --defaults  --framework akka-http --outputPath /tmp/src/main/scala \
  --client --specPath /tmp/spec.yml --packageName com.example \
  --server --specPath /tmp/spec.yml --packageName com.example
```

Hope this helps!

**Comment by sammy-da** [comment]
Thanks for the reply...

Personally i'd rather go the "pin everything" route, and so my option is to manually get hold of `guardrail-all` JAR.
(and since it's just a JAR and not a coursier app, I might as well download it from maven and run with `java`)

**Comment by blast-hardcheese** [comment]
Well, it's not a jar, it's a pom that points at the different modules
