### ISSUE TITLE
Generate complete servers, currently only success responses are generated

### ISSUE THREAD

**Issue by blast-hardcheese** [guardrail-dev/guardrail#19]
Problem
=======
Currently, servers are generated with the "best" status code being chosen as the response type for the Handler function.

This prevents servers from returning more than one response type without enabling the `x-scala-raw-response` escape hatch, bypassing safety entirely.

Proposed solution
=================

Along with every function in a server definition, also provide a `${operationId}Response` sealed abstract class or trait, as well as a companion object to handle response marshalling for the different instances of `${operationId}Response`, as well as aliased constructors for status codes.

Example
=======

```
trait FooHandler {
  // Spec says getFoo responds with:
  //   200: Foo
  //   404: Unit
  def getFoo(respond: getFooResponse.type)(id: Long): Future[getFooResponse]
}
```

```
new FooHandler {
  def getFoo(respond: getFooResponse.type)(id: Long): Future[getFooResponse] = {
    dao.getFoo(id) // OptionT[Future, Foo]
      .fold(respond.NotFound) { value =>
        respond.OK(value)
      }
  }
}
```

**Comment by dsilvasc** [comment]
Quick note for search engines: I think `x-scala-raw-response` meant `x-server-raw-response` here.

**Comment by blast-hardcheese** [comment]
@dsilvasc Good call, opened an issue to track this.
