### ISSUE TITLE
Array<Long> is not supported in query parameters

### ISSUE THREAD

**Issue by plapinsc** [guardrail-dev/guardrail#190]
The following swagger definition:
```
    /WTF:
    get:
      operationId: "wtf"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
        required: false
        type: "array"
        items:
          type: "integer"
          format: "int64"
        collectionFormat: "multi"
      responses:
        200:
          description: "successful operation"
```

generates a method with `Iterable[String]` input parameters instead of `Iterable[Long]`: 
`def wtf(respond: Resource.wtfResponse.type)(id: Option[Iterable[String]] = None): scala.concurrent.Future[Resource.wtfResponse]`

the expected result is:
`def wtf(respond: Resource.wtfResponse.type)(id: Option[Iterable[Long]] = None): scala.concurrent.Future[Resource.wtfResponse]`

To quickly mitigate the issue, I wanted to implement it with String and parse long by myself, but:
https://github.com/twilio/guardrail/issues/184

**Comment by plapinsc** [comment]
Quick workaround: `x-scala-type: "Iterable[Long]"` seems to be working...

**Comment by rtfpessoa** [comment]
@blast-hardcheese if I wanted to fix this where should I start looking?

**Comment by blast-hardcheese** [comment]
@plapinsc Which version of guardrail was this happening on?

@rtfpessoa Depending on the answer, likely [`propMeta`](https://github.com/twilio/guardrail/blob/d6f2dbb74d37cd8374b0c9304bde8f4e4a6bc272/modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala#L259-L270).

That being said, this got upended in 0.44.0 due to the switch to OpenAPI 3.x; to save yourself some effort, I'd check to make sure this is still broken in master (or with what's in #192, as that'll be reviewed and merged at some point this week).

The easiest way to test this would be to just modify `modules/sample/src/main/resources/server1.yaml` and run `runtimeSuite` in sbt, examining the generated result in `modules/sample-*`

**Comment by plapinsc** [comment]
Our guardrail version is: `0.43.0`

**Comment by rtfpessoa** [comment]
At least a handful of versions before and including `0.44.0` have this problem.
Will try to check master.

**Comment by rtfpessoa** [comment]
@blast-hardcheese seems like this still happens in `0.45.1` will try to look at your suggestion when I get some time.

**Comment by blast-hardcheese** [comment]
Excellent! Feel free to follow up here if things are not going as you expect, I may be able to dig up some more pointers

**Comment by rtfpessoa** [comment]
@blast-hardcheese tried to look into this today but never had to work with a free codebase and following the flow seems quite hard to grasp.
Do you have any other ideas where it might be loosing the initial read value of ("integer", "int64") to "string"?

The only things I was able to check was that the initial array seems fine, but then when propMeta is invoked the items type change to string somehow.

**Comment by blast-hardcheese** [comment]
A passable tool for debugging local issues is to `~cli scala --client --specPath modules/sample/src/main/resources/alias.yaml --outputPath modules/sample-akkaHttp/target/generated --packageName alias.client.akkaHttp --framework akka-http` in the sbt console, as well as `() = println(...)` inside `for` comprehensions to track down where values are doing different things than what you expect.

Narrowing it down to `propMeta` is not at all surprising, but figuring out exactly what's wrong will require runtime analysis, as it's likely something like `ArraySchema { items = ObjectSchema { schema = LongSchema {} } }` or similar coming out of the swagger-parser data model that we are not correctly analyzing and representing in our generated code.

**Comment by rtfpessoa** [comment]
I just generated with `./cli.sh scala --server --specPath modules/sample/src/main/resources/tes1.yaml --outputPath modules/sample-akkaHttp/target/generated --packageName tes1 --framework akka-http`

Where `tes1.yaml` a file with the spec above.

Anyway here is the content of method around the code:

```
def routes(handler: FileHandler)(implicit mat: akka.stream.Materializer): Route = {
    {
      get(path("commit" / LongNumber / "files")(commitId => (parameter(Symbol("fileIds").as[Long].*).map(xs => Option(xs).filterNot(_.isEmpty)).apply & parameter(Symbol("fileNames").as[String].*).map(xs => Option(xs).filterNot(_.isEmpty)).apply)((fileIds, fileNames) => discardEntity(complete(handler.commitCommitIdFiles(commitCommitIdFilesResponse)(commitId, fileIds, fileNames))))))
    }
  }
```

And the full full Routes.scala:

```
/*
 * This file was generated by Guardrail (https://github.com/twilio/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package tes1.file
import akka.http.scaladsl.model._
import akka.http.scaladsl.model.headers.RawHeader
import akka.http.scaladsl.unmarshalling.{ Unmarshal, Unmarshaller, FromEntityUnmarshaller, FromRequestUnmarshaller, FromStringUnmarshaller }
import akka.http.scaladsl.marshalling.{ Marshal, Marshaller, Marshalling, ToEntityMarshaller, ToResponseMarshaller }
import akka.http.scaladsl.server.Directives._
import akka.http.scaladsl.server.{ Directive, Directive0, Directive1, ExceptionHandler, MalformedHeaderRejection, MissingFormFieldRejection, Rejection, Route }
import akka.http.scaladsl.util.FastFuture
import akka.stream.{ IOResult, Materializer }
import akka.stream.scaladsl.{ FileIO, Keep, Sink, Source }
import akka.util.ByteString
import io.circe.Decoder
import cats.{ Functor, Id }
import cats.data.EitherT
import cats.implicits._
import scala.concurrent.{ ExecutionContext, Future }
import scala.language.higherKinds
import scala.language.implicitConversions
import java.io.File
import java.security.MessageDigest
import java.util.concurrent.atomic.AtomicReference
import scala.util.{ Failure, Success }
import scala.language.higherKinds
import _root_.tes1.Implicits._
import _root_.tes1.AkkaHttpImplicits._
import _root_.tes1.definitions._
trait FileHandler { def commitCommitIdFiles(respond: FileResource.commitCommitIdFilesResponse.type)(commitId: Long, fileIds: Option[Iterable[Long]] = None, fileNames: Option[Iterable[String]] = None): scala.concurrent.Future[FileResource.commitCommitIdFilesResponse] }
object FileResource {
  def discardEntity: Directive0 = extractMaterializer.flatMap { implicit mat => 
    extractRequest.flatMap { req => 
      req.discardEntityBytes().future
      Directive.Empty
    }
  }
  def routes(handler: FileHandler)(implicit mat: akka.stream.Materializer): Route = {
    {
      get(path("commit" / LongNumber / "files")(commitId => (parameter(Symbol("fileIds").as[Long].*).map(xs => Option(xs).filterNot(_.isEmpty)).apply & parameter(Symbol("fileNames").as[String].*).map(xs => Option(xs).filterNot(_.isEmpty)).apply)((fileIds, fileNames) => discardEntity(complete(handler.commitCommitIdFiles(commitCommitIdFilesResponse)(commitId, fileIds, fileNames))))))
    }
  }
  sealed abstract class commitCommitIdFilesResponse(val statusCode: StatusCode)
  case class commitCommitIdFilesResponseOK(value: User) extends commitCommitIdFilesResponse(StatusCodes.OK)
  case object commitCommitIdFilesResponseNotFound extends commitCommitIdFilesResponse(StatusCodes.NotFound)
  object commitCommitIdFilesResponse {
    implicit val commitCommitIdFilesTRM: ToResponseMarshaller[commitCommitIdFilesResponse] = Marshaller { implicit ec => 
      resp => commitCommitIdFilesTR(resp)
    }
    implicit def commitCommitIdFilesTR(value: commitCommitIdFilesResponse)(implicit ec: scala.concurrent.ExecutionContext): scala.concurrent.Future[List[Marshalling[HttpResponse]]] = value match {
      case r @ commitCommitIdFilesResponseOK(value) =>
        Marshal(value).to[ResponseEntity].map {
          entity => Marshalling.Opaque {
            () => HttpResponse(r.statusCode, entity = entity)
          } :: Nil
        }
      case r: commitCommitIdFilesResponseNotFound.type =>
        scala.concurrent.Future.successful(Marshalling.Opaque {
          () => HttpResponse(r.statusCode)
        } :: Nil)
    }
    def apply[T](value: T)(implicit ev: T => commitCommitIdFilesResponse): commitCommitIdFilesResponse = ev(value)
    implicit def OKEv(value: User): commitCommitIdFilesResponse = OK(value)
    def OK(value: User): commitCommitIdFilesResponse = commitCommitIdFilesResponseOK(value)
    def NotFound: commitCommitIdFilesResponse = commitCommitIdFilesResponseNotFound
  }
}
```

**Comment by blast-hardcheese** [comment]
#1407 resolves this

**Comment by blast-hardcheese** [comment]
Pardon for the delay here, this is now resolved.
