### ISSUE TITLE
Support customizing types

### ISSUE THREAD

**Issue by yaroot** [guardrail-dev/guardrail#44]
There's 2 problem in most codegen tools today:

- they generate stringly typed code, we need more refined types
- they generate low quality ADTs because the protocol definition/spec is not well designed, or the spec is so complicated that you need another layer of abstraction

briefly discussed with @blast-hardcheese at scalamatsuri, writing it down here so anyone interested can discuss here and explore in the future

**Comment by blast-hardcheese** [comment]
One other point we discussed was supporting refinement types or other validated types; this could be a way to support the validation extensions in swagger, which are currently completely ignored.

**Comment by blast-hardcheese** [comment]
This seems supported for all non-container types as of #112 . I'm keeping this issue to ensure support is eventually added to the containers as well.

**Comment by blast-hardcheese** [comment]
With #1407 I think this is finally able to be closed. All custom type resolvers are all defined in the same place now, so necessary overrides are available everywhere.
