### ISSUE TITLE
Please make `using tags as package name` as a optional feature

### ISSUE THREAD

**Issue by UkonnRa** [guardrail-dev/guardrail#476]
## Background

Not all swagger authors use `tags` to mark the jvm packages, in fact, some authors just use `tags` as a ignorable mark.

## Expected Feature

Make `using tags as package name` as a optional feature, so that it will generate a large route instead of generating several packages

**Comment by blast-hardcheese** [comment]
This is actually something I intended to remove long ago. It has already been deprecated for some time, and should just be deleted.

For the time being, you can use `x-jvm-package` to explicitly set the package, which will override the `tags`

The work required to remove this feature is to delete [this block](https://github.com/twilio/guardrail/blob/6bcb5a61b94299a66a781a0e8a4b5bcf2f927bec/modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala#L122-L132), and then ensure that any tests that were using this feature are either updated to work correctly (if they used it incidentally) or just deleted outright.

Thank you!

**Comment by blast-hardcheese** [comment]
For those interested in tackling this, the work required to remove this feature is to delete [this block](https://github.com/twilio/guardrail/blob/6bcb5a61b94299a66a781a0e8a4b5bcf2f927bec/modules/codegen/src/main/scala/com/twilio/guardrail/generators/SwaggerGenerator.scala#L122-L132), and then ensure that any tests that were using this feature are either updated to work correctly (if they used it incidentally) or just deleted outright.

**Comment by UkonnRa** [comment]
Although I know `x-jvm-package` is a solution, but unfortunately, sometimes I have to use the swagger file written by others, who may not want to add such fields for some reasons... So please release the feature, THX a lot

**Comment by blast-hardcheese** [comment]
This has been resolved in #1403, thanks!
