### ISSUE TITLE
Server generation with authorization (oauth) integration

### ISSUE THREAD

**Issue by Stinger911** [guardrail-dev/guardrail#90]
I need to generate server which works with OAuth authorization. In swagger I've defined 'securityDefinitions' and use it in the endpoint declarations. But no difference in generated code either I use securityDefinitions or not.
Hot to generate server with OAuth authorization, or how can I inject additional directive into route builder?

**Comment by Stinger911** [comment]
Thanks a lot. This approach is enough for our goals.

**Comment by blast-hardcheese** [comment]
@Stinger911 If you have a moment to document the approach you settled on, that would be very helpful -- keeping this issue open for now

**Comment by Stinger911** [comment]
Ok, I'll try to prepare documentation part relating to this issue. But I think that your comment is the enough documentation itself :)
Although I'll try.

**Comment by blast-hardcheese** [comment]
Closed due to the workaround being sufficient here, as well as the new first-class authentication support coming for http4s likely giving renewed interest in first-class authentication support. Thank you!
