### ISSUE TITLE
Getting "Error: Missing client name" when `tracing=true`

### ISSUE THREAD

**Issue by metasim** [guardrail-dev/guardrail#95]
I'm using `guardrail` via the sbt plugin:

```scala
addSbtPlugin("com.twilio" % "sbt-guardrail" % "0.37.1-M1")
```

I'm attempting to create an `akka-http` server.  When I run `guardrail`, sbt just reports `Error: Missing client name`. I'm assuming it comes from here:

https://github.com/twilio/guardrail/blob/1bd986b1cc0082aefa0fa21ddf6ff2aea6768f0e/modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala#L160-L164

The offending swagger file is available here:

https://gist.github.com/metasim/6144abd811a5a963ae3ac7735424072f

**Comment by blast-hardcheese** [comment]
`x-scala-package` in your resources controls the name of the client; this makes sense for complex APIs with many business domains, though following `className` from https://github.com/twilio/guardrail/blob/master/modules/codegen/src/main/scala/com/twilio/guardrail/ServerGenerator.scala#L60 suggests it's not currently possible to provide a fallback directly via a configuration parameter.

It should be a straightforward change to defer to the `pkg` configuration parameter, however, as it should already be available in that `context`.

**Comment by sledorze** [comment]
@blast-hardcheese @metasim sorry I'm not grasping what should change..

**Comment by blast-hardcheese** [comment]
@sledorze In my initial idea, I was suggesting that the `Context` parameter on this line https://github.com/twilio/guardrail/blob/master/modules/codegen/src/main/scala/com/twilio/guardrail/ServerGenerator.scala#L34 comes directly from the configuration parameters specified in the plugin configuration, so `clientName` could be configured as an argument in the plugin:
```scala
Server(file("external/openapi-definitions/server.yaml"), pkg="com.example", tracing=true, tracingName="server")
```
and would be used via:
```scala
                label <- Target.fromOption(
                  ScalaTracingLabel(operation)
                    .map(Lit.String(_))
                    .orElse(resourceName.lastOption.map(clientName => Lit.String(s"${clientName}:${operationId}")))
                    .orElse(context.tracingName.map(name => Lit.String(s"${name}:${operationId}"))), // <-- We're pulling `tracingName` out of the context here. This would need to be threaded through from https://github.com/twilio/guardrail/blob/9ba9524/modules/codegen/src/main/scala/com/twilio/guardrail/core/CoreTermInterp.scala#L102-L103 and the related sections in the sbt and maven plugins
                  "Missing client name" // This is actually also wrong, it should be `Missing server name` or similar; this was most likely left over copy/paste from when the server generator was created
                )
```

There's one other alternative, adding another parameter to [`routes`](https://github.com/twilio/guardrail/blob/9ba952404703dc639f60bc2a7168e8de525182c2/modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpServerGenerator.scala#L405) that defaults to the server name, but if the server name is not supplied is mandatory (similar to how [clients work](https://github.com/twilio/guardrail/blob/9ba9524/modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpClientGenerator.scala#L31-L34)).

I'm finding that I actually prefer the second approach. It's the kind of string that could very easily go in a configuration file, then be supplied at boot time as a plain argument to `routes`, vs right now requiring a complete recompile (likewise if configured via plugin argument)

**Comment by sledorze** [comment]
Oh Ok, I thought there was an existing solution.
I understand now that you were discussing the feature to add, thanks.

**Comment by blast-hardcheese** [comment]
@sledorze Yes -- this occurs when `x-scala-package` is not specified in your specification file. If you specify it, you do not get this error. The reason for this discussion is that this is _not_ a requirement for generated clients.

**Comment by blast-hardcheese** [comment]
This doesn't seem to be an issue anymore, closing
